-- Aniversário da Livia — instalação completa e idempotente
create extension if not exists pgcrypto;

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  name text not null,
  invite_code text not null unique,
  max_guests integer not null default 0 check (max_guests >= 0),
  confirmed boolean not null default false,
  active boolean not null default true,
  access_count integer not null default 0,
  last_access timestamptz,
  invite_sent boolean not null default false,
  invite_type text not null default 'individual' check (invite_type in ('individual','couple')),
  couple_members jsonb,
  constraint couple_members_array check (couple_members is null or jsonb_typeof(couple_members) = 'array')
);

create table if not exists public.rsvps (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  guest_id uuid not null unique references public.guests(id) on delete cascade,
  presence text not null check (presence in ('Sim','Não')),
  food text,
  message text,
  guest_data jsonb not null default '{}'::jsonb,
  email text,
  phone text
);

create table if not exists public.rsvp_email_deliveries (
  id bigint generated by default as identity primary key,
  guest_id uuid not null references public.guests(id) on delete cascade,
  rsvp_id uuid not null references public.rsvps(id) on delete cascade,
  rsvp_updated_at timestamptz not null,
  claimed_at timestamptz not null default now(),
  sent_at timestamptz,
  failed_at timestamptz,
  constraint rsvp_email_deliveries_version_key unique (rsvp_id, rsvp_updated_at)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.guest_access_sessions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  guest_id uuid not null references public.guests(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_access timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.invite_login_attempts (
  id bigint generated always as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  network_hash text,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index if not exists invite_attempts_user_time_idx on public.invite_login_attempts(user_id, attempted_at desc);
create index if not exists invite_attempts_network_time_idx on public.invite_login_attempts(network_hash, attempted_at desc);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admin_users where user_id = auth.uid() and active); $$;

create or replace function public.create_guest_with_invite(
  guest_name text,
  guest_invite_type text default 'individual',
  guest_couple_members jsonb default null,
  guest_max_guests integer default 0,
  guest_invite_sent boolean default false
)
returns public.guests
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  code_alphabet constant text := '23456789ABCDEFGHJKLMNPQRSTUVWXYZ';
  generated_code text;
  random_bytes bytea;
  code_position integer;
  created_guest public.guests;
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo necessário' using errcode = '42501';
  end if;

  if nullif(trim(guest_name), '') is null then
    raise exception 'Nome do convite é obrigatório' using errcode = '22023';
  end if;

  if guest_invite_type not in ('individual', 'couple') then
    raise exception 'Tipo de convite inválido' using errcode = '22023';
  end if;

  if guest_max_guests < 0 then
    raise exception 'Quantidade de acompanhantes inválida' using errcode = '22023';
  end if;

  loop
    generated_code := '';
    random_bytes := gen_random_bytes(8);

    for code_position in 0..7 loop
      generated_code := generated_code || substr(
        code_alphabet,
        (get_byte(random_bytes, code_position) % length(code_alphabet)) + 1,
        1
      );
    end loop;

    begin
      insert into public.guests (
        name, invite_code, invite_type, couple_members, max_guests,
        confirmed, active, access_count, invite_sent
      ) values (
        trim(guest_name), generated_code, guest_invite_type,
        case when guest_invite_type = 'couple' then guest_couple_members else null end,
        guest_max_guests, false, true, 0, coalesce(guest_invite_sent, false)
      )
      returning * into created_guest;

      return created_guest;
    exception when unique_violation then
      -- Uma colisão é extremamente improvável; gere outro código se ocorrer.
    end;
  end loop;
end;
$$;

create or replace function public.update_guest_details(target_guest_id uuid, guest_name text, guest_invite_type text, guest_couple_members jsonb, guest_max_guests integer, guest_invite_sent boolean)
returns public.guests language plpgsql security definer set search_path = public as $$
declare updated_guest public.guests;
begin
  if not public.is_admin() then raise exception 'Acesso administrativo necessário' using errcode = '42501'; end if;
  if nullif(trim(guest_name), '') is null then raise exception 'Nome do convite é obrigatório' using errcode = '22023'; end if;
  if guest_invite_type not in ('individual','couple') then raise exception 'Tipo de convite inválido' using errcode = '22023'; end if;
  if guest_max_guests < 0 then raise exception 'Quantidade de acompanhantes inválida' using errcode = '22023'; end if;
  update public.guests set name=trim(guest_name),invite_type=guest_invite_type,couple_members=case when guest_invite_type='couple' then guest_couple_members else null end,max_guests=guest_max_guests,invite_sent=coalesce(guest_invite_sent,false)
  where id=target_guest_id returning * into updated_guest;
  if updated_guest.id is null then raise exception 'Convidado não encontrado' using errcode = 'P0002'; end if;
  return updated_guest;
end; $$;

create or replace function public.set_guest_invite_sent(target_guest_id uuid, next_invite_sent boolean)
returns public.guests language plpgsql security definer set search_path = public as $$
declare updated_guest public.guests;
begin
  if not public.is_admin() then raise exception 'Acesso administrativo necessário' using errcode = '42501'; end if;
  update public.guests set invite_sent=coalesce(next_invite_sent,false) where id=target_guest_id returning * into updated_guest;
  if updated_guest.id is null then raise exception 'Convidado não encontrado' using errcode = 'P0002'; end if;
  return updated_guest;
end; $$;

create or replace function public.set_guest_active(target_guest_id uuid, next_active boolean)
returns public.guests language plpgsql security definer set search_path = public as $$
declare updated_guest public.guests;
begin
  if not public.is_admin() then raise exception 'Acesso administrativo necessário' using errcode = '42501'; end if;
  update public.guests set active=next_active where id=target_guest_id returning * into updated_guest;
  if updated_guest.id is null then raise exception 'Convidado não encontrado' using errcode = 'P0002'; end if;
  if not next_active then update public.guest_access_sessions set revoked_at=now() where guest_id=target_guest_id and revoked_at is null; end if;
  return updated_guest;
end; $$;

create or replace function public.save_admin_rsvp(target_guest_id uuid, submitted_email text, submitted_food text, submitted_guest_data jsonb, submitted_message text, submitted_phone text, submitted_presence text)
returns public.rsvps language plpgsql security definer set search_path = public as $$
declare target_guest public.guests; saved_rsvp public.rsvps; companion_count integer;
begin
  if not public.is_admin() then raise exception 'Acesso administrativo necessário' using errcode = '42501'; end if;
  if submitted_presence not in ('Sim','Não') then raise exception 'Presença inválida' using errcode = '22023'; end if;
  select * into target_guest from public.guests where id=target_guest_id;
  if target_guest.id is null then raise exception 'Convidado não encontrado' using errcode = 'P0002'; end if;
  companion_count := case when jsonb_typeof(coalesce(submitted_guest_data->'companions','[]'::jsonb))='array' then jsonb_array_length(coalesce(submitted_guest_data->'companions','[]'::jsonb)) else 0 end;
  if companion_count > target_guest.max_guests then raise exception 'Quantidade de acompanhantes excede o limite do convite' using errcode = '22023'; end if;
  insert into public.rsvps(guest_id,presence,food,message,guest_data,email,phone)
  values(target_guest_id,submitted_presence,submitted_food,submitted_message,coalesce(submitted_guest_data,'{}'::jsonb),submitted_email,submitted_phone)
  on conflict(guest_id) do update set presence=excluded.presence,food=excluded.food,message=excluded.message,guest_data=excluded.guest_data,email=excluded.email,phone=excluded.phone,updated_at=now()
  returning * into saved_rsvp;
  update public.guests set confirmed=true where id=target_guest_id;
  return saved_rsvp;
end; $$;

create or replace function public.delete_admin_rsvp(target_rsvp_id uuid)
returns boolean language plpgsql security definer set search_path = public as $$
declare deleted_guest_id uuid;
begin
  if not public.is_admin() then raise exception 'Acesso administrativo necessário' using errcode = '42501'; end if;
  delete from public.rsvps where id=target_rsvp_id returning guest_id into deleted_guest_id;
  if deleted_guest_id is null then return false; end if;
  update public.guests set confirmed=false where id=deleted_guest_id;
  return true;
end; $$;


create or replace function public.register_guest_access(target_guest_id uuid)
returns void language plpgsql security definer set search_path = public
as $$ begin
  update public.guests set access_count = access_count + 1, last_access = now() where id = target_guest_id and active;
  if not found then raise exception 'Convite inválido ou inativo'; end if;
end; $$;

create or replace function public.current_guest_id()
returns uuid language sql stable security definer set search_path = public
as $$ select guest_id from public.guest_access_sessions where user_id = auth.uid() and revoked_at is null; $$;

create or replace function public.get_current_guest_profile()
returns table(id uuid, name text, max_guests integer, confirmed boolean, active boolean, invite_type text, couple_members jsonb)
language sql stable security definer set search_path = public
as $$
  select g.id,g.name,g.max_guests,g.confirmed,g.active,g.invite_type,g.couple_members
  from public.guests g where g.id = public.current_guest_id() and g.active;
$$;

create or replace function public.save_current_rsvp(submitted_email text, submitted_food text, submitted_guest_data jsonb, submitted_message text, submitted_phone text, submitted_presence text)
returns setof public.rsvps language plpgsql security definer set search_path = public
as $$
declare
  gid uuid := public.current_guest_id();
  target_guest public.guests;
  companion_count integer;
begin
  if gid is null then raise exception 'Sessão de convite inválida'; end if;
  if submitted_presence not in ('Sim','Não') then raise exception 'Presença inválida'; end if;
  select * into target_guest from public.guests where id=gid and active;
  if target_guest.id is null then raise exception 'Convite inválido ou inativo'; end if;
  companion_count := case when jsonb_typeof(coalesce(submitted_guest_data->'companions','[]'::jsonb))='array' then jsonb_array_length(coalesce(submitted_guest_data->'companions','[]'::jsonb)) else 0 end;
  if companion_count > target_guest.max_guests then raise exception 'Quantidade de acompanhantes excede o limite do convite' using errcode = '22023'; end if;
  insert into public.rsvps(guest_id,presence,food,message,guest_data,email,phone)
  values(gid,submitted_presence,submitted_food,submitted_message,coalesce(submitted_guest_data,'{}'::jsonb),submitted_email,submitted_phone)
  on conflict(guest_id) do update set presence=excluded.presence,food=excluded.food,message=excluded.message,guest_data=excluded.guest_data,email=excluded.email,phone=excluded.phone,updated_at=now();
  update public.guests set confirmed = true where id = gid;
  return query select * from public.rsvps where guest_id = gid;
end; $$;

alter table public.guests enable row level security;
alter table public.rsvps enable row level security;
alter table public.admin_users enable row level security;
alter table public.guest_access_sessions enable row level security;
alter table public.invite_login_attempts enable row level security;
alter table public.rsvp_email_deliveries enable row level security;

drop policy if exists guests_admin_all on public.guests;
create policy guests_admin_all on public.guests for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists rsvps_admin_all on public.rsvps;
create policy rsvps_admin_all on public.rsvps for all to authenticated using(public.is_admin()) with check(public.is_admin());
drop policy if exists rsvps_guest_select on public.rsvps;
create policy rsvps_guest_select on public.rsvps for select to authenticated using(guest_id = public.current_guest_id());

revoke all on all tables in schema public from anon;
revoke all on public.guests,public.rsvps,public.admin_users,public.guest_access_sessions,public.invite_login_attempts from authenticated;
revoke all on public.rsvp_email_deliveries from anon, authenticated;
revoke all on sequence public.rsvp_email_deliveries_id_seq from anon, authenticated;
grant select on public.guests,public.rsvps to authenticated;
revoke all on function public.register_guest_access(uuid) from public,anon,authenticated;
grant execute on function public.register_guest_access(uuid) to service_role;
revoke all on function public.create_guest_with_invite(text,text,jsonb,integer,boolean) from public,anon;
grant execute on function public.create_guest_with_invite(text,text,jsonb,integer,boolean) to authenticated;
revoke all on function public.update_guest_details(uuid,text,text,jsonb,integer,boolean),public.set_guest_invite_sent(uuid,boolean),public.set_guest_active(uuid,boolean),public.save_admin_rsvp(uuid,text,text,jsonb,text,text,text),public.delete_admin_rsvp(uuid) from public,anon;
grant execute on function public.update_guest_details(uuid,text,text,jsonb,integer,boolean),public.set_guest_invite_sent(uuid,boolean),public.set_guest_active(uuid,boolean),public.save_admin_rsvp(uuid,text,text,jsonb,text,text,text),public.delete_admin_rsvp(uuid) to authenticated;
grant execute on function public.is_admin(),public.current_guest_id(),public.get_current_guest_profile(),public.save_current_rsvp(text,text,jsonb,text,text,text) to authenticated;

-- Depois de criar o usuário no Supabase Auth:
-- insert into public.admin_users(user_id) values ('UUID-DO-USUARIO');
