create table if not exists public.rsvp_email_deliveries (
  id bigint generated by default as identity primary key,
  guest_id uuid not null references public.guests(id) on delete cascade,
  rsvp_id uuid not null references public.rsvps(id) on delete cascade,
  rsvp_updated_at timestamptz not null,
  claimed_at timestamptz not null default now(),
  sent_at timestamptz,
  failed_at timestamptz,
  constraint rsvp_email_deliveries_version_key
    unique (rsvp_id, rsvp_updated_at)
);

alter table public.rsvp_email_deliveries enable row level security;

-- No client policies are intentional. Only the Edge Function service role can
-- claim, complete, or release a delivery.
revoke all on table public.rsvp_email_deliveries from anon, authenticated;
revoke all on sequence public.rsvp_email_deliveries_id_seq from anon, authenticated;
